=== badrishb/NCP-assignment1/Lab 10-eval-17-10-20/assessment/bank.dtd
<!ELEMENT bank (customer*)>
<!ELEMENT customer (custdetails,custtransac,custacc)>
<!ELEMENT custdetails (custid,custname,custage,custgen,custadd,custbranch)>
<!ELEMENT custid (#PCDATA)>
<!ELEMENT custname (#PCDATA)>
<!ELEMENT custage (#PCDATA)>
<!ELEMENT custgen (#PCDATA)>
<!ELEMENT custadd (#PCDATA)>
<!ELEMENT custbranch (#PCDATA)>
<!ELEMENT custtransac (nowith,nodep,allwith,alldep)>
<!ELEMENT nowith (#PCDATA)>
<!ELEMENT nodep (#PCDATA)>
<!ELEMENT allwith (with*)>
<!ELEMENT with (withamt,wbalbef,wbalaft,wdate)>
<!ELEMENT withamt (#PCDATA)>
<!ELEMENT wbalbef (#PCDATA)>
<!ELEMENT wbalaft (#PCDATA)>
<!ELEMENT wdate (#PCDATA)>
<!ELEMENT alldep (dep*)>
<!ELEMENT dep (depamt,dbalbef,dbalaft,ddate)>
<!ELEMENT depamt (#PCDATA)>
<!ELEMENT dbalbef (#PCDATA)>
<!ELEMENT dbalaft (#PCDATA)>
<!ELEMENT ddate (#PCDATA)>
<!ELEMENT custacc (acctype,accstart,accbal,accloans*)>
<!ELEMENT acctype (#PCDATA)>
<!ELEMENT accstart (#PCDATA)>
<!ELEMENT accbal (#PCDATA)>
<!ELEMENT accloans (loanamt,loandate,loanint)>
<!ELEMENT loanamt (#PCDATA)>
<!ELEMENT loandate (#PCDATA)>
<!ELEMENT loanint (#PCDATA)>

<!--<!ELEMENT patname (#PCDATA)>
<!ELEMENT patid (#PCDATA)>
<!ELEMENT patage (#PCDATA)>
<!ELEMENT disease (#PCDATA)>
<!ELEMENT tdname (#PCDATA)>
<!ELEMENT roomno (#PCDATA)>-->

=== badrishb/NCP-assignment1/Lab 10-eval-17-10-20/assessment/bank.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="bank.css"?>
<?xml-stylesheet href="bank.xsl" type="text/xsl"?>
<!DOCTYPE bank SYSTEM "bank.dtd">
<bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="bank.xsd">

	<customer>
		<custdetails>
			<custid>
				1
			</custid>
			<custname>
				Badrish
			</custname>
			<custage>
				21
			</custage>
			<custgen>
				Male
			</custgen>
			<custadd>
				Perambur
			</custadd>
			<custbranch>
				Anna Nagar
			</custbranch>
			
		</custdetails>
		<custtransac>
			<nowith>3</nowith>
			<nodep>2</nodep>
			<allwith>
				<with>
					<withamt>100</withamt>
					<wbalbef>1000</wbalbef>
					<wbalaft>900</wbalaft>
					<wdate>3</wdate>
				</with>
				<with>
					<withamt>150</withamt>
					<wbalbef>900</wbalbef>
					<wbalaft>750</wbalaft>
					<wdate>7</wdate>
				</with>
				<with>
					<withamt>120</withamt>
					<wbalbef>750</wbalbef>
					<wbalaft>630</wbalaft>
					<wdate>12</wdate>
				</with>
			</allwith>
			<alldep>
				<dep>
					<depamt>130</depamt>
					<dbalbef>630</dbalbef>
					<dbalaft>760</dbalaft>
					<ddate>13</ddate>
				</dep>
				<dep>
					<depamt>200</depamt>
					<dbalbef>760</dbalbef>
					<dbalaft>960</dbalaft>
					<ddate>16</ddate>
				</dep>
			</alldep>
			
		</custtransac>
		<custacc>
			<acctype>Premium</acctype>
			<accstart>2</accstart>
			<accbal>960</accbal>
			<accloans>
				<loanamt>800</loanamt>
				<loandate>2</loandate>
				<loanint>10%</loanint>
			</accloans>
			
		</custacc>
	</customer>
	<customer>
		<custdetails>
			<custid>
				2
			</custid>
			<custname>
				Ashwin
			</custname>
			<custage>
				JKL
			</custage>
			<custgen>
				Male
			</custgen>
			<custadd>
				SaiBaba Colony
			</custadd>
			<custbranch>
				Ettimadai
			</custbranch>

		</custdetails>
		<custtransac>
			<nowith>3</nowith>
			<nodep>2</nodep>
			<allwith>
				<with>
					<withamt>10</withamt>
					<wbalbef>1000</wbalbef>
					<wbalaft>990</wbalaft>
					<wdate>2</wdate>
				</with>
				<with>
					<withamt>160</withamt>
					<wbalbef>990</wbalbef>
					<wbalaft>830</wbalaft>
					<wdate>4</wdate>
				</with>
				<with>
					<withamt>120</withamt>
					<wbalbef>830</wbalbef>
					<wbalaft>710</wbalaft>
					<wdate>9</wdate>
				</with>
			</allwith>
			<alldep>
				<dep>
					<depamt>120</depamt>
					<dbalbef>710</dbalbef>
					<dbalaft>830</dbalaft>
					<ddate>10</ddate>
				</dep>
				<dep>
					<depamt>200</depamt>
					<dbalbef>830</dbalbef>
					<dbalaft>1030</dbalaft>
					<ddate>13</ddate>
				</dep>
			</alldep>

		</custtransac>
		<custacc>
			<acctype>Checking</acctype>
			<accstart>1</accstart>
			<accbal>1030</accbal>
			<accloans>
				<loanamt>400</loanamt>
				<loandate>1</loandate>
				<loanint>5%</loanint>
			</accloans>

		</custacc>
	</customer>
	<customer>
		<custdetails>
			<custid>
				3
			</custid>
			<custname>
				Nisha
			</custname>
			<custage>
				21
			</custage>
			<custgen>
				Female
			</custgen>
			<custadd>
				Perambur
			</custadd>
			<custbranch>
				Anna Nagar
			</custbranch>

		</custdetails>
		<custtransac>
			<nowith>3</nowith>
			<nodep>2</nodep>
			<allwith>
				<with>
					<withamt>100</withamt>
					<wbalbef>1000</wbalbef>
					<wbalaft>900</wbalaft>
					<wdate>3</wdate>
				</with>
				<with>
					<withamt>150</withamt>
					<wbalbef>900</wbalbef>
					<wbalaft>750</wbalaft>
					<wdate>7</wdate>
				</with>
				<with>
					<withamt>120</withamt>
					<wbalbef>750</wbalbef>
					<wbalaft>630</wbalaft>
					<wdate>12</wdate>
				</with>
			</allwith>
			<alldep>
				<dep>
					<depamt>130</depamt>
					<dbalbef>630</dbalbef>
					<dbalaft>760</dbalaft>
					<ddate>13</ddate>
				</dep>
				<dep>
					<depamt>200</depamt>
					<dbalbef>760</dbalbef>
					<dbalaft>960</dbalaft>
					<ddate>16</ddate>
				</dep>
			</alldep>

		</custtransac>
		<custacc>
			<acctype>Premium</acctype>
			<accstart>2</accstart>
			<accbal>960</accbal>
			<accloans>
				<loanamt>800</loanamt>
				<loandate>2</loandate>
				<loanint>10%</loanint>
			</accloans>

		</custacc>
	</customer>
</bank>
